# Generated by Django 4.2.2 on 2023-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(choices=[('mozzarella', 'Mozzarella'), ('parmesan', 'Parmesan'), ('provolone', 'Provolone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(choices=[('marinara', 'Marinara'), ('alfredo', 'Alfredo'), ('ranch', 'Ranch'), ('buffalo', 'Buffalo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('sausage', 'Sausage'), ('chicken', 'Chicken'), ('peppers', 'Peppers')], max_length=50),
        ),
    ]
