# Generated by Django 4.2.2 on 2023-07-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0003_alter_cart_pizzas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sauce',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('sausage', 'Sausage'), ('cheese', 'Cheese'), ('veggie', 'Veggie')], default='pepperoni', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
