# Generated by Django 4.2.2 on 2023-07-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0004_remove_pizza_cheese_remove_pizza_sauce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=6),
        ),
    ]
